import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../app/components/navbar";
import Sidebar from "./components/sidebar";
import RFQForm from "./components/RFQ";
import Account from "./components/account";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Loomiz Buyer Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Sidebar />
       
        <main>{children}</main>
      </body>
    </html>
  );
}

